name: PHP Coding Standards Fixer

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/backend

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer:3

      - name: Run PHP CS Fixer
        run: |
          php-cs-fixer fix --using-cache=no

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto apply php-cs-fixer changes
